name:                sbvExample

dependencies:
- base >= 4.7 && < 5
- sbv

executables:
  sbvExample:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -Wall
